Arrays library

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Any dimension array

In [4]:
a = np.array(7)
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(a)
print(b)
print(c)
print(d)

7
[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Indexing

In [11]:
print(a)
print(b[1])
print(c[1, 2])
print(d[0, 1, 1])

print(b[-1])
print(c[-1, -2])
print(d[-1, -2, -3])

7
2
6
5
4
5
7


Slice

In [17]:
print(arr[1: 3])
print(arr[3:])
print(d[0, 1: 2])

[2 3]
[4 5]
[[4 5 6]]


Iteration

In [21]:
for element in arr:
    print(element)

for arrr in d:
    for arrrr in arrr:
        for element in arrrr:
            print(element)

# loop multi dimension as one dimension
for element in np.nditer(d):
    print(element)

1
2
3
4
5
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


Conditions

In [24]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
four_indexes = np.where(arr == 4)
print(four_indexes)

for index in four_indexes:
    print(arr[index])

(array([3, 5, 6], dtype=int64),)
[4 4 4]
